server:
  port: 2922

spring:
  application:
    name: vehicle
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: #数据库账号
    password: #数据库密码
  thymeleaf:
    cache: false  #开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    static-path-pattern: /static/**